### PR TITLE
Updated Top button and Error page

### PR DESCRIPTION
**Pull request by VyjayantiN**
I have updated the "top"button and added related CSS to enhance GUI. I have also added some words in the error page not found file. Please check and accept my pull request.

### CODE REVIEW

**Comment by jineshnagori** [comment]
> I have updated the "top"button and added related CSS to enhance GUI. I have also added some words in the error page not found file. Please check and accept my pull request.

Hey @VyjayantiN 
Please resolve the conflicts

**Comment by VyjayantiN** [comment]
@jineshnagori 
I had to add a class to the button in index.html in order to style them.
I guess there isn't another way to do it. Please check the main section of the index.html  where I added a class named "cd" to the button.

**Comment by jineshnagori** [comment]
> @jineshnagori
> I had to add a class to the button in index.html in order to style them.
> I guess there isn't another way to do it. Please check the main section of the index.html where I added a class named "cd" to the button.

Yes but you need to resolve the conflicts unless I wouldn’t be able to merge your request.

**Comment by VyjayantiN** [comment]
Please check.
I've resolved the conflict.

**Pull request merged**
